baseURL: https://www.theapplemancan.uk/
languageCode: en-GB
title: Martin Hayes
theme: apples
pluralizeListTitles: false
copyright: This work is dual-licensed under MIT & GPL v3
paginate: 2
summaryLength: 13
author:
  name: Martin Hayes
  email: hello@theapplemancan.uk
taxonomies:
  tag: tags
params:
  description: Orchardist
  publisher: Martin Hayes
  publisherLogo: assets/img/logo.png
  publisherLogoWidth: 220
  publisherLogoHeight: 220
  twitter: IndiegoHugo
  facebook: IndiegoHugo
  email: hello@indiego.org.uk
  googleplus: 112354208488638707199
  fbapp_id: 206433049934562
  tel: "+447398474064"
